#!/usr/bin/env node

const esbuild = require('esbuild');
const path = require('path');
const clc = require('cli-color');
const watch = process.argv.indexOf('--watch') >= 0;

const files = ['assets/js/frontend.js'];

for (const file of files) {
    build(file);
}

function build(entry) {
    const ext = path.extname(entry);
    const watchOptions = {
        onRebuild(error, result) {
            if (error) console.error('watch build failed:', error);
            else console.log('rebuild ', entry);
        },
    };
    const regex = new RegExp(ext + '$');
    esbuild
        .build({
            entryPoints: [entry],
            outfile: entry.replace(regex, '.min' + ext),
            bundle: true,
            watch: !watch ? null : watchOptions,
            minify: !watch,
        })
        .then((result) => {
            const message = watch
                ? clc.blue(`watching ${entry} ...`)
                : clc.green(`Success! ${entry} minified`);
            console.log(message);
        });
}
